# Setup
title:               ksprsk.me
tagline:             '지극히 개인적이고 지루하고 현학적인'
description:         '"Don&#39;t think, but look!"<br> — Wittgenstein'
url:                 https://ksprsk.me
baseurl:             ''
permalink:           pretty

# About/contact
author:
  name:              지병찬(Chi, Byoungchan)
  url:               https://x.com/ksprsk_
  email:             bchan052415@gmail.com

# Gems
plugins: []

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
